.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. labyrinth_qt test_labyrinth_qt
clean: FORCE
	$(MAKE) -C .. labyrinth_qt_clean test_labyrinth_qt_clean
check: FORCE
	$(MAKE) -C .. test_labyrinth_qt_check
labyrinth-qt labyrinth-qt.exe: FORCE
	 $(MAKE) -C .. labyrinth_qt
